server:
  port: 8099

operation:
  server: http://192.168.1.250:8084/api/openapi

picture:
  url:  d:\\AlarmPicture


  secretKey: Zgx123..!

#自定义连接url地址
#kediou:
#  url: http://192.168.1.188:304









#配置通用tk mapper
mapper:
  mappers:
    - com.zgx.tkmybatis.MyMapper
  not-empty: false
  identity: MYSQL

#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql